<a href="https://colab.research.google.com/github/samuelcoflo/Analitica-de-Negocios/blob/main/Naive_bayes_Samuel_Correa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Modelo de preaprobacion - Naive Bayes**

0. Se procede con la carga de las librerias de trabajo

In [ ]:
import numpy as np #Funciones Matematicas
import pandas as pd #Comunicacion con excel
from sklearn.naive_bayes import GaussianNB #Modelo de Clasificacion
from sklearn.metrics import confusion_matrix #Metrica de evaluacion

1. Se cargan los datos

In [ ]:
nxl='/content/0. SolicitantesCrédito(USD)_NaiveBayes(L).xlsx'
XDB=pd.read_excel(nxl,sheet_name=2) #Traigo los datos
XDB.dropna() #Eliminar celdas vacias, datos faltantes

#Seleccionamos variables de interes
XDB=XDB[['Edad','Ingresos','Egresos','Cuota (COP)','PreApr']]

#Datos de Entrada- np.array() - Convertir a numeros
XD=np.array(XDB[['Edad','Ingresos','Egresos','Cuota (COP)']])
#Datos de Salida - Valor deseado - Que aprenda el modelo
yd=np.array(XDB['PreApr'])



Edad    Ingresos      Egresos  Cuota (COP)  PreApr
0       38  1356.14400  1685.622667    18.375890       1
1       51   286.01600   364.462000     5.062492       1
2       37   517.46325   629.208889    10.287688       0
3       29   473.27000   551.616889    15.458878       1
4       42   750.09175   806.715778    24.995180       1
...    ...         ...          ...          ...     ...
5837    48  1207.84800   753.801111    27.043503       1
5838    31  1472.77200   953.812889    25.579568       1
5839    38   773.01975   672.910667    21.508792       1
5840    43   635.50175   780.691556    11.047468       1
5841    37  1419.26675  1169.838444    36.356182       1

[5842 rows x 5 columns]

2. Implementamos modelo

In [ ]:
mnb=GaussianNB() #Llamamos el modelo
mnb.fit(XD,yd) #Entrenamos el modelo
ydp=mnb.predict(XD) #Muestra los datos de salida que el obtuvo

#Parametros del modelo por cada categoria - PreApr/PreNeg
u=mnb.theta_ #Se estiman medidas
sigma=np.sqrt(mnb.var_) #Se estiman desviaciones

#Las variaciones de las variables
LI=u-sigma #Limite inferior
LS=u+sigma #Limite superior

print('la media de las variables por categoria:')
print(u)
print('El limite inferior de la variacion de las variables por categoria es:')
print(LI)
print('El limite superior de la variacion de las variables por categoria es:')
print(LS)

#Metrica de Evaluacion - Como se comporto el modelo identificando la preApr-Preneg
cm=confusion_matrix(yd,ydp) #Matriz de confusion
print("La matriz de confusion es:")
print(cm)

la media de las variables por categoria:
[[  40.98411626  431.42680644  401.54995644   16.88529983]
 [  41.10752688 1029.98947251  900.19312144   43.3269839 ]]
El limite inferior de la variacion de las variables por categoria es:
[[ 28.77108358 105.62889147  58.77709557 -12.88412769]
 [ 28.85646196 557.55604444 374.75974307 -21.65436704]]
El limite superior de la variacion de las variables por categoria es:
[[  53.19714893  757.22472141  744.32281731   46.65472735]
 [  53.35859181 1502.42290058 1425.62649981  108.30833484]]
La matriz de confusion es:
[[2563  396]
 [1192 1691]]


4. Se procede con la evaluacion del modelo

In [ ]:
VN=cm[0,0] #Verdaderos Negativos
VP=cm[1,1] #Verdaderos Positivos
FN=cm[1,0] #Falsos Negativos
FP=cm[0,1] #Falsos Positivos

Exactitud=(VP+VN)/len(XD)
print('La exactitud del modelo es:', Exactitud) # Comportamiento general

TE=(FN+FP)/len(XD)
print('La tasa de error del modelo es:', TE) #Porcentaje Equivocaciones

Sensibilidad=VP/(VP+FP)
print('La sensibilidad del modelo es:', Sensibilidad) #Comportamiento positivo

Especificidad=VN/(VN+FN)
print('La especificidad del modelo es:', Especificidad) #Comportamiento negativo

Precision=VP/(VP+FN)
print('La precición del modelo es:', Precision) #Comportamiento positivo

PredNeg=VN/(VN+FP)
print('La probabilidad de predicción negativa del modelo es:', PredNeg) #Comportamiento negativo

La exactitud del modelo es: 0.7281752824375214
La tasa de error del modelo es: 0.2718247175624786
La sensibilidad del modelo es: 0.8102539530426449
La especificidad del modelo es: 0.6825565912117177
La precición del modelo es: 0.5865417967395075
La probabilidad de predicción negativa del modelo es: 0.8661710037174721


5. Que pasa con una sola persona

In [ ]:
Xun=np.array([[3.8,1356,1686,18]]) #Esta la persona del excel
ydun=mnb.predict(Xun) #Muestra los datos de salida que el obtuvo
print(ydun)

[1]
